TMBucket/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    
     url(r'^$', 'translations.views.home_page', name='home'),
     url(r'^tms/', include('translations.urls')),
)

translations/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    
     url(r'^(\d+)/$', 'translations.views.view_tms', name='view_tms'),
     url(r'^new$', 'translations.views.new_tm', name='new_tm'),
)

translations/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class TM(models.Model):

    def get_absolute_url(self):
        return reverse('view_tms', args=[self.id])

class TransUnit(models.Model):
    source = models.TextField(default='')
    target = models.TextField(default='')
    tm = models.ForeignKey(TM, default=None)

translations/forms.py
from django import forms
from translations.models import TransUnit

EMPTY_SOURCE_ERROR = "You can't submit empty source string"
EMPTY_TARGET_ERROR = "You can't submit empty target string"

class TransUnitForm(forms.models.ModelForm):
    class Meta:
        model = TransUnit
        fields = ('source', 'target')
        widgets = {
        'source': forms.fields.TextInput(
            attrs={
            'placeholder': "Enter source text", 
            'class' : "form-control",
            }),
        'target' :forms.fields.TextInput(
            attrs={
            'placeholder': "Enter translation text", 
            'class' : "form-control",
            })
            } 
        error_messages = {
        'source': {'required': EMPTY_SOURCE_ERROR},
        'target': {'required': EMPTY_TARGET_ERROR}
        }
        

translations/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError

from translations.models import TransUnit, TM
from translations.forms import TransUnitForm

# Create your views here.
def home_page(request):
    return render(request, 'home.html', {'form': TransUnitForm()})
def view_tms(request, tm_id):
    tm_to_show = TM.objects.get(id=tm_id)
    error = None
    form = TransUnitForm()
    if request.method == 'POST':
        form = TransUnitForm(data=request.POST)
        if form.is_valid():
            new_transunit =TransUnit.objects.create(
                source=request.POST['source'],
                target=request.POST['target'],
                tm=tm_to_show)
            return redirect(tm_to_show)
    
    return render(request, 'tms.html', {'tm': tm_to_show, 'form': form})
def new_tm(request):
    form = TransUnitForm(data = request.POST)

    if form.is_valid():
        new_tm = TM.objects.create()
        TransUnit.objects.create(
            source=request.POST['source'], 
            target=request.POST['target'],
            tm=new_tm)
        return redirect(new_tm)
    else:
        return render(request,'home.html', {'form': form})
    

    

translations/templates/base.html
<!DOCTYPE html>
<html lang='en'>
<head>
    <title>TMBucket</title>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'/>
    <link href='/static/bootstrap/css/bootstrap.min.css' rel='stylesheet' media='screen'/>
    <link href="/static/base.css" rel="stylesheet" media="screen" />
</head>
<body>
    <div class='container'>
    <div class='row'>
    <div class='col-md-8 col-md-offset-2'>
    <div class='text-center'>
    <h1>{% block header_text %} {% endblock %}</h1>
    <form method="POST" action='{% block form_action %} {% endblock %}'>
        {{ form.source }}
        {{ form.target }}
        <button action="submit" class='form-control' id='id_add_translations'>Add</button>
        {% csrf_token %}
        {% if form.errors %}
        <div class='form-group has-error'>
            <span class='help-block'>{{ form.source.errors }}</span>
            <span class='help-block'>{{ form.target.errors }}</span>
            
        </div>
        {% endif %}
    </form>
    </div>    
    </div>
</div>
<div class='row'>
    <div class='col-md-8 col-md-offset-2'>
    {% block table%}
    {% endblock %}
</div>


</div>
</div>
</body>
</html>

translations/templates/home.html

{% extends 'base.html' %}

    {% block header_text %}Start filling your TMBucket{% endblock %}

    {% block form_action %}{% url 'new_tm' %}{% endblock %}
    


translations/templates/tms.html

{% extends 'base.html' %}

    {% block header_text %}Your TMBucket{% endblock%}
    
    {% block form_action %}{% url 'view_tms' tm.id %}{% endblock %}
    
    {% block table %}
    <table id="id_translation_table" class='table'>
        {% for trans_unit in tm.transunit_set.all %}
        <tr>
            <td>{{ forloop.counter }}: {{ trans_unit.source }}</td>
            <td>{{ trans_unit.target }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endblock %}
